name: CI + CD (Docker)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------- CI ----------
      - name: Build Docker image
        run: docker build -t cicd-app .

      # ---------- CD ----------
      - name: Deploy to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh -o StrictHostKeyChecking=no aqib@localhost "
            docker stop cicd-app || true
            docker rm cicd-app || true
            docker run -d \
              --name cicd-app \
              -p 3000:3000 \
              cicd-app
          "

